### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by cyj1208** [kk42yy/DeMoSeg#1]
在运行Train_DeMoSeg时发生以下报错：
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1779,0,0], thread: [75,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1779,0,0], thread: [76,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [5251,0,0], thread: [127,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
  0%|                                                     | 0/5 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/Train_DeMoSeg.py", line 13, in <module>
    demoseg_trainer.run_train()
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/trainer/DeMoSeg_Trainer.py", line 191, in run_train
    epoch_loss[idx] = self.training_epoch(next(self.train_loader))
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/trainer/BaseTrainer.py", line 299, in training_epoch
    l = self.loss(output, lbl)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/loss/loss_scheduler.py", line 41, in forward
    l = weights[0] * self.loss(*inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/monai/losses/dice.py", line 800, in forward
    dice_loss = self.dice(input, target)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/monai/losses/dice.py", line 158, in forward
    target = one_hot(target, num_classes=n_pred_ch)
  File "/root/miniconda3/lib/python3.10/site-packages/monai/networks/utils.py", line 192, in one_hot
    labels = o.scatter_(dim=dim, index=labels.long(), value=1)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
这个错误该如何解决呢？

**Comment by kk42yy** [comment]
可能是环境配置造成的，我们基于`python3.8`开发的DeMoSeg，请参照ReadMe文件进行环境配置，确保每个库的版本一致。

**Comment by cyj1208** [comment]
在改正上面的错误后，我又遇到了问题，希望能得到您的指导：
2024-09-23 18:43:53,768 - Epoch: 0, current lr: 0.01
  0%|                                                     | 0/5 [00:00<?, ?it/s]Exception in background worker 1:
 applying transform <monai.transforms.compose.Compose object at 0x7f4276f21c40>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
TypeError: 'list' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 50, in producer
    item_b = apply_transform(transform, item_b)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform [<monai.transforms.compose.Compose object at 0x7f4276f21c40>, Compose ( [SpatialTransform( independent_scale_for_each_axis = False, p_rot_per_sample = 0.2, p_scale_per_sample = 0.2, p_el_per_sample = 0, data_key = 'data', label_key = 'seg', patch_size = [128, 128, 128], patch_center_dist_from_border = None, do_elastic_deform = False, alpha = (0, 0), sigma = (0, 0), do_rotation = True, angle_x = (-0.5235987755982988, 0.5235987755982988), angle_y = (-0.5235987755982988, 0.5235987755982988), angle_z = (-0.5235987755982988, 0.5235987755982988), do_scale = True, scale = (0.7, 1.4), border_mode_data = 'constant', border_cval_data = 0, order_data = 3, border_mode_seg = 'constant', border_cval_seg = -1, order_seg = 1, random_crop = False, p_rot_per_axis = 1, p_independent_scale_per_axis = 1 ), GaussianNoiseTransform( p_per_sample = 0.1, data_key = 'data', noise_variance = (0, 0.1), p_per_channel = 1, per_channel = False ), GaussianBlurTransform( p_per_sample = 0.2, different_sigma_per_channel = True, p_per_channel = 0.5, data_key = 'data', blur_sigma = (0.5, 1.0), different_sigma_per_axis = False, p_isotropic = 0 ), BrightnessMultiplicativeTransform( p_per_sample = 0.15, data_key = 'data', multiplier_range = (0.75, 1.25), per_channel = True ), ContrastAugmentationTransform( p_per_sample = 0.15, data_key = 'data', contrast_range = (0.75, 1.25), preserve_range = True, per_channel = True, p_per_channel = 1 ), SimulateLowResolutionTransform( order_upsample = 3, order_downsample = 0, channels = None, per_channel = True, p_per_channel = 0.5, p_per_sample = 0.25, data_key = 'data', zoom_range = (0.5, 1), ignore_axes = None ), GammaTransform( p_per_sample = 0.1, retain_stats = True, per_channel = True, data_key = 'data', gamma_range = (0.7, 1.5), invert_image = True ), GammaTransform( p_per_sample = 0.3, retain_stats = True, per_channel = True, data_key = 'data', gamma_range = (0.7, 1.5), invert_image = False ), MirrorTransform( p_per_sample = 1, data_key = 'data', label_key = 'seg', axes = (0, 1, 2) ), MaskTransform( apply_to_channels = [0, 1, 2, 3], seg_key = 'seg', data_key = 'data', set_outside_to = 0, mask_idx_in_seg = 0 ), RemoveLabelTransform( output_key = 'seg', input_key = 'seg', replace_with = 0, remove_label = -1 ), RenameTransform( delete_old = True, out_key = 'label', in_key = 'seg' ), RenameTransform( delete_old = True, out_key = 'image', in_key = 'data' ), NumpyToTensor( keys = ['image', 'label'], cast_to = 'float' )] )]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/io/array.py", line 274, in __call__
    raise RuntimeError(
RuntimeError: LoadImage cannot find a suitable reader for file: ('/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0000.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0001.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0002.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0003.nii.gz').
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x7f4276f21100>, <monai.data.image_reader.PILReader object at 0x7f4276f21430>].


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f444180d310>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 65, in producer
    item_b = apply_transform(monai_trans, item_b)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f4276f21c40>
Exception in background worker 0:
 applying transform <monai.transforms.compose.Compose object at 0x7f4276f21c40>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
TypeError: 'list' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 50, in producer
    item_b = apply_transform(transform, item_b)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform [<monai.transforms.compose.Compose object at 0x7f4276f21c40>, Compose ( [SpatialTransform( independent_scale_for_each_axis = False, p_rot_per_sample = 0.2, p_scale_per_sample = 0.2, p_el_per_sample = 0, data_key = 'data', label_key = 'seg', patch_size = [128, 128, 128], patch_center_dist_from_border = None, do_elastic_deform = False, alpha = (0, 0), sigma = (0, 0), do_rotation = True, angle_x = (-0.5235987755982988, 0.5235987755982988), angle_y = (-0.5235987755982988, 0.5235987755982988), angle_z = (-0.5235987755982988, 0.5235987755982988), do_scale = True, scale = (0.7, 1.4), border_mode_data = 'constant', border_cval_data = 0, order_data = 3, border_mode_seg = 'constant', border_cval_seg = -1, order_seg = 1, random_crop = False, p_rot_per_axis = 1, p_independent_scale_per_axis = 1 ), GaussianNoiseTransform( p_per_sample = 0.1, data_key = 'data', noise_variance = (0, 0.1), p_per_channel = 1, per_channel = False ), GaussianBlurTransform( p_per_sample = 0.2, different_sigma_per_channel = True, p_per_channel = 0.5, data_key = 'data', blur_sigma = (0.5, 1.0), different_sigma_per_axis = False, p_isotropic = 0 ), BrightnessMultiplicativeTransform( p_per_sample = 0.15, data_key = 'data', multiplier_range = (0.75, 1.25), per_channel = True ), ContrastAugmentationTransform( p_per_sample = 0.15, data_key = 'data', contrast_range = (0.75, 1.25), preserve_range = True, per_channel = True, p_per_channel = 1 ), SimulateLowResolutionTransform( order_upsample = 3, order_downsample = 0, channels = None, per_channel = True, p_per_channel = 0.5, p_per_sample = 0.25, data_key = 'data', zoom_range = (0.5, 1), ignore_axes = None ), GammaTransform( p_per_sample = 0.1, retain_stats = True, per_channel = True, data_key = 'data', gamma_range = (0.7, 1.5), invert_image = True ), GammaTransform( p_per_sample = 0.3, retain_stats = True, per_channel = True, data_key = 'data', gamma_range = (0.7, 1.5), invert_image = False ), MirrorTransform( p_per_sample = 1, data_key = 'data', label_key = 'seg', axes = (0, 1, 2) ), MaskTransform( apply_to_channels = [0, 1, 2, 3], seg_key = 'seg', data_key = 'data', set_outside_to = 0, mask_idx_in_seg = 0 ), RemoveLabelTransform( output_key = 'seg', input_key = 'seg', replace_with = 0, remove_label = -1 ), RenameTransform( delete_old = True, out_key = 'label', in_key = 'seg' ), RenameTransform( delete_old = True, out_key = 'image', in_key = 'data' ), NumpyToTensor( keys = ['image', 'label'], cast_to = 'float' )] )]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/io/array.py", line 274, in __call__
    raise RuntimeError(
RuntimeError: LoadImage cannot find a suitable reader for file: ('/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0000.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0001.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0002.nii.gz', '/root/autodl-tmp/DeMoSeg-main/DeMoSeg/DataAndOutput/Dataset/DataFile/BraTS2018/imagesTr/Brats18_CBICA_ABB_1_0003.nii.gz').
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x7f4276f21100>, <monai.data.image_reader.PILReader object at 0x7f4276f21430>].


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f444180d310>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 65, in producer
    item_b = apply_transform(monai_trans, item_b)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f4276f21c40>
using pin_memory on device 0
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/Train_DeMoSeg.py", line 13, in <module>
    demoseg_trainer.run_train()
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/trainer/DeMoSeg_Trainer.py", line 192, in run_train
    epoch_loss[idx] = self.training_epoch(next(self.train_loader))
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 205, in __next__
    item = self.__get_next_item()
  File "/root/autodl-tmp/DeMoSeg-main/DeMoSeg/training/dataloader/MultiThreadDataLoader.py", line 190, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Process finished with exit code 1

**Comment by kk42yy** [comment]
方便把你的`conda list`贴一下吗

**Comment by cyj1208** [comment]
万分感谢，以下是我的conda list：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
absl-py                   1.4.0                    pypi_0    pypi
aiofiles                  22.1.0                   pypi_0    pypi
aiosqlite                 0.18.0                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
batchgenerators           0.25                     pypi_0    pypi
beautifulsoup4            4.11.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
cachetools                5.3.0                    pypi_0    pypi
certifi                   2021.5.30        py38h06a4308_0    defaults
cffi                      1.14.6           py38h400218f_0    defaults
chardet                   4.0.0           py38h06a4308_1003    defaults
charset-normalizer        3.1.0                    pypi_0    pypi
cmake                     3.26.0                   pypi_0    pypi
comm                      0.1.2                    pypi_0    pypi
conda                     4.10.3           py38h06a4308_0    defaults
conda-package-handling    1.7.3            py38h27cfd23_1    defaults
contourpy                 1.0.7                    pypi_0    pypi
cryptography              3.4.7            py38hd23ed53_0    defaults
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.6                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
filelock                  3.10.0                   pypi_0    pypi
fonttools                 4.39.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
google-auth               2.16.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.51.3                   pypi_0    pypi
idna                      2.10               pyhd3eb1b0_0    defaults
imageio                   2.35.1                   pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
ipykernel                 6.21.3                   pypi_0    pypi
ipython                   8.11.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.4                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
json5                     0.9.11                   pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.0.3                    pypi_0    pypi
jupyter-core              5.2.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.4.0                    pypi_0    pypi
jupyter-server-fileid     0.8.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter-server-ydoc       0.6.1                    pypi_0    pypi
jupyter-ydoc              0.2.3                    pypi_0    pypi
jupyterlab                3.6.1                    pypi_0    pypi
jupyterlab-language-pack-zh-cn 3.6.post0                pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.20.0                   pypi_0    pypi
jupyterlab-widgets        3.0.5                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
linecache2                1.0.0                    pypi_0    pypi
lit                       15.0.7                   pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
monai                     1.3.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
nbclassic                 0.5.3                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.10                   pypi_0    pypi
nbformat                  5.7.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
notebook                  6.5.3                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0    defaults
packaging                 23.0                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       21.1.3           py38h06a4308_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.1.1                    pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.22.1                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.14.0                   pypi_0    pypi
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.10               h12debd9_8    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.1                   pypi_0    pypi
readline                  8.1                  h27cfd23_0    defaults
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel_yaml               0.15.100         py38h27cfd23_0    defaults
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4                      pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0    defaults
stack-data                0.6.2                    pypi_0    pypi
supervisor                4.2.5                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tensorboard               2.12.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.10               hbc83047_0    defaults
tomli                     2.0.1                    pypi_0    pypi
torch                     2.0.0+cu118              pypi_0    pypi
torchvision               0.15.1+cu118             pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
traceback2                1.4.0                    pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0    defaults
widgetsnbextension        4.0.5                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
y-py                      0.5.9                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0    defaults
ypy-websocket             0.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults

**Comment by kk42yy** [comment]
请按照`ReadMe`和`requirements.txt`中的环境配置，我们只支持以下的配置，其他的版本冲突会出现上述问题：
**python=3.8**
**pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6**
**monai==1.2.0**

**Comment by cyj1208** [comment]
好的好的，感谢您的解答
